### ISSUE TITLE
AttributeError: module 'nvidia.dali.ops' has no attribute 'nvJPEGDecoder'

### ISSUE THREAD

**Issue by hangon666** [scaleway/frontalization#5]
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    frontalize(saved_model, datapath, 3)
  File "test.py", line 16, in frontalize
    test_pipe = ImagePipeline(datapath, image_size=128, random_shuffle=False, batch_size=mtest)
  File "/home/hanchao/Wu/frontalization/data.py", line 108, in __init__
    self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
AttributeError: module 'nvidia.dali.ops' has no attribute 'nvJPEGDecoder'

When i try to run the code, this error ocurred, how can i fix it ?

**Comment by hangon666** [comment]
My version of nvidia.dali is 0.16.0, what's the version used in this project?

**Comment by opetrova** [comment]
@hangon666 try changing 
self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB) to
self.decode = ops.ImageDecoder(device = 'mixed', output_type = types.RGB)

**Comment by hangon666** [comment]
@opetrova 
thanks for your reply, I have changed my nvidia.dali version to 0.15.0,
but when i try to test on pytorch==1.1.0, it seems dismatch, and when i test on pytorch==0.4.1, it reminds me that i can't load the pre-trained model
could you tell me which version of pytorch should l use?

**Comment by anshen666** [comment]
> Traceback (most recent call last): File "test.py", line 32, in frontalize(saved_model, datapath, 3) File "test.py", line 16, in frontalize test_pipe = ImagePipeline(datapath, image_size=128, random_shuffle=False, batch_size=mtest) File "/home/hanchao/Wu/frontalization/data.py", line 108, in **init** self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB) AttributeError: module 'nvidia.dali.ops' has no attribute 'nvJPEGDecoder'
> 
> When i try to run the code, this error ocurred, how can i fix it ?

请问方便留个联系方式吗？这个项目一直没跑通，可以留个联系方式交流一下吗？
